<a href="https://colab.research.google.com/github/tanvirnwu/PyTorch--Python/blob/main/Foundation_of_PyTorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.0.1+cu118


**Creating Tensors**

In [2]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

7

In [5]:
# Vector

vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
# MATRIX

MATRIX = torch.tensor([[7, 8],
                        [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX.shape

torch.Size([2, 2])

In [11]:
MATRIX[1]

tensor([ 9, 10])

In [12]:
MATRIX[0]

tensor([7, 8])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 4, 5],
                        [5, 6, 7]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]])

In [14]:
TENSOR.shape

torch.Size([1, 3, 3])

In [15]:
TENSOR.ndim

3

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]])

In [17]:
TENSOR_2 = torch.tensor([[[1, 2, 3],
                        [3, 4, 5],
                        [5, 6, 7]],

                         [[1, 2, 3],
                        [3, 4, 5],
                        [5, 6, 7]]
                         ] )

TENSOR_2

tensor([[[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]],

        [[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]])

In [18]:
TENSOR_2.ndim, TENSOR_2.shape

(3, torch.Size([2, 3, 3]))

In [19]:
TENSOR_3 = torch.tensor([[[1, 2, 3],
                        [3, 4, 5],
                        [5, 6, 7]],

                         [[1, 2, 3],
                        [3, 4, 5],
                        [5, 6, 7]],

                         [[1, 2, 3],
                        [3, 4, 5],
                        [5, 6, 7]]
                         ] )

TENSOR_3.ndim, TENSOR_3.shape

(3, torch.Size([3, 3, 3]))

# Random Tensors

In [20]:
# Create a random tensor

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.2359, 0.9703, 0.1212, 0.7048],
        [0.5966, 0.0172, 0.1332, 0.4739],
        [0.0895, 0.6936, 0.8341, 0.6125]])

In [21]:
random_tensor.ndim

2

In [22]:
random_tensor.shape

torch.Size([3, 4])

In [23]:
# Create a random tensor

random_tensor = torch.rand(1, 6, 4)
random_tensor

tensor([[[0.2760, 0.6257, 0.6983, 0.6958],
         [0.2468, 0.8085, 0.3466, 0.1125],
         [0.5530, 0.9888, 0.7321, 0.3594],
         [0.6322, 0.2378, 0.7294, 0.6497],
         [0.6967, 0.5338, 0.8109, 0.7390],
         [0.2136, 0.1266, 0.1852, 0.3033]]])

In [24]:
random_image_size_tensor = torch.rand(size =(224,224,3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

Zeros and Ones

In [25]:
# Create Zeros and Ones
zeros = torch.zeros(size= (3,4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [26]:
ones = torch.ones(size= (3,4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [27]:
ones.dtype, random_tensor.dtype

(torch.float32, torch.float32)

### Creating a arange of tensors and tensor-like

In [28]:
# Use torch.arange()

torch.arange(0, 10)

tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
one_to_thousand = torch.arange(start = 1, end = 10, step =77 )
one_to_thousand

tensor([1])

In [30]:
one_to_ten = torch.arange(start = 1, end = 11, step =1 )
one_to_ten

tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [31]:
one_to_ten.shape

torch.Size([10])

In [32]:
# Tensor Like
ten_zeros = torch.zeros_like(input = one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor Data Types

In [33]:
# Float 32 Tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = None)
float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [34]:
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype = torch.float16)
float_16_tensor, float_16_tensor.dtype

(tensor([3., 6., 9.], dtype=torch.float16), torch.float16)

In [35]:
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype = None,  #Data Type
                               device = None, #GPU/CPU
                               requires_grad = False) # Track Gradients

float_32_tensor, float_32_tensor.dtype

(tensor([3., 6., 9.]), torch.float32)

In [36]:
# Converting Data Type
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [37]:
nn = float_16_tensor*float_32_tensor
nn, nn.dtype

(tensor([ 9., 36., 81.]), torch.float32)

In [38]:
int_32_tensor  = torch.tensor([3, 4 , 2], dtype = torch.int32)
int_32_tensor

tensor([3, 4, 2], dtype=torch.int32)

In [39]:
float_16_tensor*int_32_tensor

tensor([ 9., 24., 18.], dtype=torch.float16)

### Manipulation of Tensors (Tensor Operations)

In [40]:
# Create a tensor of values and add a number to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [41]:
# Multiply it by 10
tensor * 10

tensor([10, 20, 30])


Notice how the tensor values above didn't end up being tensor([110, 120, 130]), this is because the values inside the tensor don't change unless they're reassigned.

In [42]:
# Tensors don't change unless reassigned
tensor

tensor([1, 2, 3])

In [43]:
# Subtract and reassign
tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [44]:
# Add and reassign
tensor = tensor + 10
tensor

tensor([1, 2, 3])


PyTorch also has a bunch of built-in functions like torch.mul() (short for multiplication) and torch.add() to perform basic operations.

In [45]:
# Can also use torch functions
torch.multiply(tensor, 10)

tensor([10, 20, 30])

In [46]:
# Original tensor is still unchanged
tensor

tensor([1, 2, 3])

#### Matrix Multiplication

In [47]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])


In [48]:
import torch
tensor = torch.tensor([1, 2, 3])
tensor.shape

torch.Size([3])

In [49]:
# Element-wise matrix multiplication
tensor * tensor

tensor([1, 4, 9])

In [50]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [51]:
# Can also use the "@" symbol for matrix multiplication, though not recommended
tensor @ tensor

tensor(14)

In [52]:
tensor

tensor([1, 2, 3])

In [53]:
# Matrix Multiplication by hand
1*1 + 2*2 + 3*3

14


You can do matrix multiplication by hand but it's not recommended.

The in-built torch.matmul() method is faster.

In [54]:
%%time
# Matrix multiplication by hand
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: user 221 µs, sys: 32 µs, total: 253 µs
Wall time: 261 µs


tensor(14)

In [55]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 34 µs, sys: 5 µs, total: 39 µs
Wall time: 42.2 µs


tensor(14)

One of the most common errors in deep learning (shape errors)
Because much of deep learning is multiplying and performing operations on matrices and matrices have a strict rule about what shapes and sizes can be combined, one of the most common errors you'll run into in deep learning is shape mismatches.

In [56]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)
# This will produce an error as expected because of the shape missmatch.

RuntimeError: ignored

We can make matrix multiplication work between tensor_A and tensor_B by making their inner dimensions match.

One of the ways to do this is with a transpose (switch the dimensions of a given tensor).

You can perform transposes in PyTorch using either:

torch.transpose(input, dim0, dim1) - where input is the desired tensor to transpose and dim0 and dim1 are the dimensions to be swapped.
tensor.T - where tensor is the desired tensor to transpose

In [57]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [58]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [59]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])



You can also use torch.mm() which is a short for torch.matmul(). bold text

In [60]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

In [61]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])



###Finding the min, max, mean, sum, etc (aggregation)
Now we've seen a few ways to manipulate tensors, let's run through a few ways to aggregate them (go from more values to less values).

First we'll create a tensor and then find the max, min, mean and sum of it.

In [62]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [63]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


You can also do the same as above with torch methods.

In [64]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

### Positional min/max
You can also find the index of a tensor where the max or minimum occurs with torch.argmax() and torch.argmin() respectively.

This is helpful incase you just want the position where the highest (or lowest) value is and not the actual value itself (we'll see this in a later section when using the softmax activation function).

In [65]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where max value occurs: 8
Index where min value occurs: 0


### Change tensor datatype
If one tensor is in torch.float64 and another is in torch.float32, you might run into some errors.

But there's a fix.

You can change the datatypes of tensors using torch.Tensor.type(dtype=None) where the dtype parameter is the datatype you'd like to use.

First we'll create a tensor and check it's datatype (the default is torch.float32).

In [66]:
# Create a tensor and check its datatype
sample_tensor = torch.arange(10., 100., 10.)
sample_tensor.dtype, sample_tensor

(torch.float32, tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.]))

In [67]:
# Create a float16 tensor
tensor_float16 = sample_tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [68]:
# Create a int8 tensor
tensor_int8 = sample_tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

### Reshaping, stacking, squeezing and unsqueezing
Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values inside them.

To do so, some popular methods are:

In [69]:
# Create a Tensor

x = torch.arange(1., 10.)
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [70]:
# Add an extra dimention
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [71]:
# Add an extra dimention
x_reshaped = x.reshape(9, 1)
x_reshaped, x_reshaped.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [72]:
# Change the View
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))


Remember though, changing the view of a tensor with torch.view() really only creates a new view of the same tensor.

So changing the view changes the original tensor too.

In [73]:
# Changing z changes x
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))


If we wanted to stack our new tensor on top of itself five times, we could do so with torch.stack().

In [74]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=0) # try changing dim to dim=1 and see what happens
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [75]:
# Stack tensors on top of each other
x_stacked = torch.stack([x, x, x, x], dim=1) # dim = 1 means stack columns-wise
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])


####How about removing all single dimensions from a tensor?

To do so you can use torch.squeeze() (I remember this as squeezing the tensor to only have dimensions over 1).

In [76]:
x_reshaped

tensor([[5.],
        [2.],
        [3.],
        [4.],
        [5.],
        [6.],
        [7.],
        [8.],
        [9.]])

In [77]:
x_reshaped= x_reshaped.reshape(1,9)
x_reshaped

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [78]:
x_reshaped.squeeze()

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [79]:
x_reshaped.squeeze().size()

torch.Size([9])

In [80]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()

print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shape: torch.Size([9])


### **And to do the reverse of torch.squeeze() you can use torch.unsqueeze() to add a dimension value of 1 at a specific index.**

In [81]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


### You can also rearrange the order of axes values with torch.permute(input, dims), where the input gets turned into a view with new dims

In [82]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3)) # Height, Width, Channels

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # Channels, Height, Width

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [83]:
x = torch.randn(2, 3, 5)
x.size()

torch.Size([2, 3, 5])

In [84]:
x

tensor([[[-0.7963,  0.6134,  1.1794, -0.9621,  1.6388],
         [-0.8928,  1.2756, -0.9238,  1.6126, -0.7292],
         [ 0.7680,  2.4192, -0.4922, -0.6502,  0.4609]],

        [[-0.5408, -0.3830, -1.1725,  0.0145,  0.5402],
         [ 1.4513,  0.4064,  0.9798, -2.6272, -1.1485],
         [-0.3889,  1.5624, -0.7264,  1.0032,  0.4538]]])

In [85]:
torch.permute(x, (2, 0, 1)).size()

torch.Size([5, 2, 3])

In [86]:
x_original[0,0,0]

tensor(0.2666)

In [87]:
x_permuted[0,0,0]

tensor(0.2666)

In [88]:
x_original[0,0,0] = 0.55
x_original[0,0,0], x_permuted[0,0,0]

(tensor(0.5500), tensor(0.5500))

### Indexing (Selecting Data from Tensor)

In [89]:
# Create a Tensor
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [90]:
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [91]:
x[0][0]

tensor([1, 2, 3])

In [92]:
x[0,0]

tensor([1, 2, 3])

In [93]:
x[0, 0, 0]

tensor(1)

In [94]:
x[0, 0, 1]

tensor(2)

In [95]:
x[0, 1, 1]

tensor(5)

In [96]:
# Select all from a target dimaention
x[:, 0]

tensor([[1, 2, 3]])

In [97]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [98]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [99]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]

tensor([1, 2, 3])


### PyTorch tensors & NumPy
Since NumPy is a popular Python numerical computing library, PyTorch has functionality to interact with it nicely.

The two main methods you'll want to use for NumPy to PyTorch (and back again) are:

* torch.from_numpy(ndarray) - NumPy array -> PyTorch tensor.
* torch.Tensor.numpy() - PyTorch tensor -> NumPy array.

**Let's try them out.**

In [100]:
# NumPy array to tensor
array = np.arange(1.0, 8.0)
array, array.shape

(array([1., 2., 3., 4., 5., 6., 7.]), (7,))

In [101]:
tensor = torch.from_numpy(array)
tensor, tensor.shape

(tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64), torch.Size([7]))

In [102]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [103]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

### Reproducibility (trying to take the random out of random)
start with random numbers -> tensor operations -> try to make better (again and again and again)

Although randomness is nice and powerful, sometimes you'd like there to be a little less randomness.

Why?

So you can perform repeatable experiments.

For example, you create an algorithm capable of achieving X performance.

And then your friend tries it out to verify you're not crazy.

How could they do such a thing?

That's where reproducibility comes in.

In other words, can you get the same (or very similar) results on your computer running the same code as I get on mine?

Let's see a brief example of reproducibility in PyTorch.

We'll start by creating two random tensors, since they're random, you'd expect them to be different right?

In [104]:
# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.2741, 0.6142, 0.8973, 0.3629],
        [0.1748, 0.2401, 0.5457, 0.7303],
        [0.5268, 0.6694, 0.3213, 0.4008]])

Tensor B:
tensor([[0.2892, 0.9977, 0.6649, 0.5646],
        [0.9323, 0.4621, 0.4027, 0.1680],
        [0.1170, 0.5063, 0.6061, 0.5141]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


Just as you might've expected, the tensors come out with different values.

But what if you wanted to created two random tensors with the same values.

As in, the tensors would still contain random values but they would be of the same flavour.

That's where torch.manual_seed(seed) comes in, where seed is an integer (like 42 but it could be anything) that flavours the randomness.

Let's try it out by creating some more flavoured random tensors.

In [105]:
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

In [106]:
# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

In [107]:
print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

### Getting a GPU

In [108]:
!nvidia-smi

Sat Jul 29 01:57:38 2023       
+-----------------------------------------------------------------------------+
| NVIDIA-SMI 525.105.17   Driver Version: 525.105.17   CUDA Version: 12.0     |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|                               |                      |               MIG M. |
|===============================+======================+======================|
|   0  Tesla T4            Off  | 00000000:00:04.0 Off |                    0 |
| N/A   46C    P8    11W /  70W |      0MiB / 15360MiB |      0%      Default |
|                               |                      |                  N/A |
+-------------------------------+----------------------+----------------------+
                                                                               
+-------

In [109]:
# Check for GPU
import torch
torch.cuda.is_available()

True

In [110]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [111]:
# Count number of devices
torch.cuda.device_count()

1

### Putting tensors (and models) on the GPU
**Note:** Putting a tensor on GPU using to(device) (e.g. some_tensor.to(device)) returns a copy of that tensor, e.g. the same tensor will be on CPU and GPU. To overwrite tensors, reassign them:

some_tensor = some_tensor.to(device)

In [112]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3]) cpu


tensor([1, 2, 3], device='cuda:0')

#### Moving tensors back to the CPU

In [115]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()

TypeError: ignored

In [117]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [118]:
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')