## **Introduction**

**[PyTorch](https://pytorch.org/)** is an open-source machine learning library developed by Facebook's AI Research lab. It’s popular in the deep learning community due to its flexibility and dynamic computation graph, which makes it easier to work with and debug. PyTorch provides a wide range of APIs for both neural networks and tensor computations. It is also known for its pythonic design, making it very straightforward and intuitive for Python developers to learn and implement deep learning algorithms. The extensive community support and plethora of tutorials and documentation available make learning and implementing models using PyTorch an enriching experience.

For more detailed information and resources, you can visit the official **[PyTorch website](https://pytorch.org/)**.

In [1]:
# Importing PyTorch, essential for deep learning tasks.
import torch

# Importing pandas for data manipulation and analysis.
import pandas as pd

# Importing numpy for numerical computations.
import numpy as np

# Importing matplotlib for data visualization.
import matplotlib.pyplot as plt

# Printing the version of PyTorch to verify installation.
print(torch.__version__)

2.0.0


## **What is Tensor?**
**Tensor:** A tensor is a multi-dimensional array that is the fundamental building block of PyTorch and many other machine learning and deep learning libraries. Tensors are similar to NumPy’s ndarrays, but they also have the additional capability to be used on GPUs for accelerated computing. Tensors are optimized for automatic differentiation (autograd) and are used as the primary data structure to build neural networks in PyTorch.

Here are a few key points about tensors:

#### **Dimentions**
- **0D Tensor:** A 0-dimensional tensor is a single number (scalar).
- **1D Tensor:** A 1-dimensional tensor is similar to a vector.
- **2D Tensor:** A 2-dimensional tensor is similar to a matrix.
- **ND Tensor:** Tensors can have three or more dimensions, allowing them to represent more complex data structures.

#### **Data Types**
- Tensors can hold data of different data types such as float, int, and boolean.

#### **Device Compatibility**
- Tensors can be moved onto any device, such as a GPU, to accelerate computing.

#### **Autograd**
- PyTorch tensors support autograd, meaning that they can automatically compute gradients or derivatives, essential for neural network training.

## **Creating Tensors**

#### **0D Tensor**

In [2]:
# Creating a 0-dimensional tensor (scalar) with the value 7 using PyTorch.
scalar = torch.tensor(7)
scalar

tensor(7)

In [3]:
# Printing the number of dimensions of the scalar tensor. Expecting 0 because it's a scalar.
print(f"Domention of Scalar is: {scalar.ndim}")

Domention of Scalar is: 0


In [4]:
# Printing the value of the scalar tensor using formatted string.
print(f"Value of Scalar is: {scalar.item()}")

Value of Scalar is: 7


#### **1D Vector**

In [5]:
# Creating a 1-dimensional tensor (vector) with two elements, both being the value 7.
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [6]:
# Printing the number of dimensions of the scalar tensor. Expecting 0 because it's a scalar.
print(f"Domention of Vector is: {vector.ndim}")

Domention of Vector is: 1


In [7]:
print(f"Shape of the Vector: {vector.shape}")

Shape of the Vector: torch.Size([2])


#### **2D Tensor: Matrix**
In this code, a 2-dimensional tensor (matrix) named MATRIX is created with the specified values in a 2x2 format. 

In [8]:
# Creating a 2-dimensional tensor (matrix) with the specified values, and displaying it.
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])
print(MATRIX)


tensor([[ 7,  8],
        [ 9, 10]])


In [9]:
# Printing the number of dimensions of the MATRIX tensor. Since MATRIX is 2-dimensional, it will return 2.
print(f"Number of Dimensions of MATRIX: {MATRIX.ndim}")

Number of Dimensions of MATRIX: 2


In [10]:
# Printing the shape of the MATRIX tensor. This will return the size of each dimension of the MATRIX.
print(f"Shape of MATRIX: {MATRIX.shape}")

Shape of MATRIX: torch.Size([2, 2])


In [11]:
# Accessing and printing the second row of the MATRIX tensor.
# Indexing is zero-based.
print(MATRIX[1])

tensor([ 9, 10])


In [12]:
# Accessing and printing the first row of the MATRIX tensor.
print(MATRIX[0])

tensor([7, 8])


#### **3D Tensor**
In this code snippet, a 3-dimensional tensor named TENSOR is created with the specified values. Using the print statement will cleanly display the TENSOR tensor when you run this code, showcasing its three-dimensional structure:

In [13]:
# Creating a 3-dimensional tensor (TENSOR) with the specified values, and displaying it.
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 4, 5],
                        [5, 6, 7]]])
print(TENSOR)

tensor([[[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]])


In [14]:
# Printing the shape and number of dimensions of the TENSOR. 
# The shape will return the size of each dimension, and ndim will return the number of dimensions.
print(f"Shape of TENSOR: {TENSOR.shape}, Number of Dimensions: {TENSOR.ndim}")

Shape of TENSOR: torch.Size([1, 3, 3]), Number of Dimensions: 3


In [15]:
# Accessing and printing the first element of the TENSOR. Since TENSOR is a 3D tensor, this will return a 2D matrix.
print(TENSOR[0])

tensor([[1, 2, 3],
        [3, 4, 5],
        [5, 6, 7]])


In [16]:
# 3D Tensor
# Creating a 3-dimensional tensor (TENSOR_2) with two 3x3 matrices, and displaying it.
TENSOR_2 = torch.tensor([[[1, 2, 3],
                          [3, 4, 5],
                          [5, 6, 7]],

                         [[1, 2, 3],
                          [3, 4, 5],
                          [5, 6, 7]]
                         ])

print(TENSOR_2)

tensor([[[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]],

        [[1, 2, 3],
         [3, 4, 5],
         [5, 6, 7]]])


In [17]:
# Printing the number of dimensions and the shape of TENSOR_2.
# .ndim returns the number of dimensions, and .shape returns the size of each dimension.
print(f"Number of Dimensions of TENSOR_2: {TENSOR_2.ndim}, Shape of TENSOR_2: {TENSOR_2.shape}")

Number of Dimensions of TENSOR_2: 3, Shape of TENSOR_2: torch.Size([2, 3, 3])


In [18]:
# 3D Tensor
# Creating a 3-dimensional tensor (TENSOR_3) with three 3x3 matrices, and displaying its number of dimensions and shape.
TENSOR_3 = torch.tensor([[[1, 2, 3],
                          [3, 4, 5],
                          [5, 6, 7]],

                         [[1, 2, 3],
                          [3, 4, 5],
                          [5, 6, 7]],

                         [[1, 2, 3],
                          [3, 4, 5],
                          [5, 6, 7]]
                         ])

# Printing the number of dimensions and the shape of TENSOR_3.
print(f"Number of Dimensions of TENSOR_3 is: {TENSOR_3.ndim}, Shape of TENSOR_3: {TENSOR_3.shape}")

Number of Dimensions of TENSOR_3 is: 3, Shape of TENSOR_3: torch.Size([3, 3, 3])


## **Creating Random Tensors**

In [19]:
# Creating a random tensor of shape (3, 4) with values uniformly distributed between 0 and 1.
random_tensor = torch.rand(3, 4)
print(random_tensor)

tensor([[0.4040, 0.1968, 0.5024, 0.5774],
        [0.0024, 0.8129, 0.9515, 0.5040],
        [0.2446, 0.2588, 0.4798, 0.1987]])


In [20]:
# Printing the number of dimensions of random_tensor using the .ndim attribute.
print(f"Number of Dimensions of random_tensor: {random_tensor.ndim}")

Number of Dimensions of random_tensor: 2


In [21]:
# Printing the shape of random_tensor using the .shape attribute.
# This will return a tuple representing the size of each dimension.
print(f"Shape of random_tensor: {random_tensor.shape}")

Shape of random_tensor: torch.Size([3, 4])


In [22]:
# Creating a 3D random tensor of shape (1, 6, 4) with values uniformly distributed between 0 and 1.
random_tensor = torch.rand(1, 6, 4)
print(random_tensor)

tensor([[[0.9727, 0.4000, 0.4697, 0.9433],
         [0.4788, 0.0810, 0.4840, 0.2424],
         [0.9889, 0.9818, 0.8022, 0.8394],
         [0.4816, 0.9432, 0.9366, 0.8859],
         [0.4099, 0.1777, 0.8083, 0.2739],
         [0.4185, 0.4140, 0.3383, 0.8796]]])


In [23]:
# Create a random tensor resembling an image size
# Generating a random tensor of shape (224, 224, 3), symbolizing an image of 224x224 pixels with 3 color channels (RGB).
random_image_size_tensor = torch.rand(size=(224, 224, 3))

# Printing the shape and number of dimensions of the generated tensor.
print(f"Shape of random_image_size_tensor: {random_image_size_tensor.shape}, Number of Dimensions: {random_image_size_tensor.ndim}")

Shape of random_image_size_tensor: torch.Size([224, 224, 3]), Number of Dimensions: 3


## **Zeros and Ones**
In PyTorch, you can easily create tensors filled exclusively with zeros or ones. These types of tensors can be particularly useful for various scenarios, such as initializing weights in neural networks, among other use cases.

#### **Creating a Zero Tensor**
You can use the torch.zeros() function to create a tensor filled with zeros. 

In [24]:
# Creating a tensor of shape (3, 3) filled with zeros
zero_tensor = torch.zeros(3, 3)
print("Zero Tensor:")
print(zero_tensor)

Zero Tensor:
tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


#### **Creating a One Tensor**
Likewise, the torch.ones() function allows you to create a tensor populated with ones. 

In [25]:
# Creating a tensor of shape (3, 3) filled with ones
one_tensor = torch.ones(3, 3)
print("\nOne Tensor:")
print(one_tensor)


One Tensor:
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [26]:
# Displaying the data types of zero_tensor and one_tensor using the .dtype attribute.
# It returns the data type of the tensor's elements.
print(f"Data type of zero_tensor: {zero_tensor.dtype}")
print(f"Data type of one_tensor: {one_tensor.dtype}")

Data type of zero_tensor: torch.float32
Data type of one_tensor: torch.float32


## **Arange of Tensors and Tensor-like**
The torch.arange() function is used to create a 1-dimensional tensor with a sequence of numbers within a specified range. 

In [27]:
# Creating a 1D tensor with a sequence of integers from 0 to 9.
arange_tensor = torch.arange(0, 10)

# Printing the created tensor.
print("Tensor created with torch.arange(0, 10):")
print(arange_tensor)

Tensor created with torch.arange(0, 10):
tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])


In [28]:
# Using torch.arange() with specified start, end, and step values.
# Creating a tensor with values starting from 1, ending before 1000, incrementing by 77.
one_to_thousand = torch.arange(start=1, end=1000, step=77)

# Printing the created tensor.
print("Tensor created with torch.arange(start=1, end=1000, step=77):")
print(one_to_thousand)

Tensor created with torch.arange(start=1, end=1000, step=77):
tensor([  1,  78, 155, 232, 309, 386, 463, 540, 617, 694, 771, 848, 925])


In [29]:
one_to_thousand.shape

torch.Size([13])

#### **Tensor-Like**
torch.zeros_like() is a practical function used in various scenarios, primarily when you need a new tensor with the same shape and properties (e.g., data type, device) as an existing tensor but want to initialize it with zeros. 

In [30]:
one_to_ten = torch.arange(1, 11)  # Creating a tensor with values from 1 to 10

# Creating a tensor named ten_zeros with the same shape and properties as one_to_ten, but filled with zeros.
ten_zeros = torch.zeros_like(input=one_to_ten)

# Printing the ten_zeros tensor
print("Tensor ten_zeros, with the same shape and properties as one_to_ten but filled with zeros:")
print(ten_zeros)

Tensor ten_zeros, with the same shape and properties as one_to_ten but filled with zeros:
tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])


## **Tensor Data Types**

#### **Float 16**

In [31]:
# Creating a tensor with floating-point values and specifying the data type as torch.float16.
float_16_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=torch.float16)

# Printing the tensor and its data type.
print(f"Tensor: {float_16_tensor}, Data Type: {float_16_tensor.dtype}")

Tensor: tensor([3., 6., 9.], dtype=torch.float16), Data Type: torch.float16


#### **Float 32**

In [32]:
# Creating a tensor with floating-point values and letting PyTorch infer the data type.
float_32_tensor = torch.tensor([3.0, 6.0, 9.0], dtype=None)

# Printing the tensor and its data type.
print(f"Tensor: {float_32_tensor}, Data Type: {float_32_tensor.dtype}")

Tensor: tensor([3., 6., 9.]), Data Type: torch.float32


In [33]:
# Creating a tensor with additional specifications: dtype, device, and requires_grad.
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],  # Data values
                               dtype=None,        # Data Type: Not explicitly set, will be inferred
                               device=None,       # Device: Not explicitly set, will use the default device (usually CPU)
                               requires_grad=False)  # Track Gradients: False

# Printing the tensor and its data type.
print(f"Tensor: {float_32_tensor}, Data Type: {float_32_tensor.dtype}")

Tensor: tensor([3., 6., 9.]), Data Type: torch.float32


In [34]:
# Element-wise multiplication between two tensors: float_16_tensor and float_32_tensor.
nn = float_16_tensor * float_32_tensor

# Printing the result tensor and its data type.
print(f"Result Tensor: {nn}, Data Type: {nn.dtype}")

Result Tensor: tensor([ 9., 36., 81.]), Data Type: torch.float32


In [35]:
# Creating a tensor with integer values and specifying the data type as torch.int32.
int_32_tensor = torch.tensor([3, 4, 2], dtype=torch.int32)

# Printing the created tensor.
print(int_32_tensor)

tensor([3, 4, 2], dtype=torch.int32)


In [36]:
float_16_tensor*int_32_tensor

tensor([ 9., 24., 18.], dtype=torch.float16)

## **Manipulation of Tensors**

In PyTorch, tensors can be manipulated in various ways to perform mathematical operations, reshape their dimensions, and more. This section explores some common tensor operations:

#### **1. Tensor Arithmetic Operations**
You can perform basic arithmetic operations on tensors, such as addition, subtraction, multiplication, and division. For example:

In [37]:
# Creating two tensors
tensor1 = torch.tensor([1, 2, 3])
tensor2 = torch.tensor([4, 5, 6])

# Addition
result_addition = tensor1 + tensor2
result_addition

tensor([5, 7, 9])

In [38]:
# Subtraction
result_subtraction = tensor1 - tensor2
result_subtraction

tensor([-3, -3, -3])

In [39]:
# Multiplication
result_multiplication = tensor1 * tensor2
result_multiplication

tensor([ 4, 10, 18])

In [40]:
# Division
result_division = tensor1 / tensor2
result_division

tensor([0.2500, 0.4000, 0.5000])

#### **2. Reshaping Tensors**
You can change the shape of a tensor using the .reshape() method or the .view() method. For example:

In [41]:
# Reshaping a tensor to a different shape
original_tensor = torch.tensor([[1, 2], [3, 4], [5, 6]])
reshaped_tensor = original_tensor.reshape(2, 3)

#### **3. Reduction Operations**
Reduction operations allow you to perform computations across the elements of a tensor. Common reduction operations include sum, mean, minimum, and maximum:

In [42]:
tensor = torch.tensor([1, 2, 3, 4, 5], dtype=torch.float32)  # Convert to float32
sum_result = torch.sum(tensor)
mean_result = torch.mean(tensor)
min_result = torch.min(tensor)
max_result = torch.max(tensor)

print("Sum:", sum_result)
print("Mean:", mean_result)
print("Min:", min_result)
print("Max:", max_result)

Sum: tensor(15.)
Mean: tensor(3.)
Min: tensor(1.)
Max: tensor(5.)


#### **4. Element-wise Functions**
PyTorch provides various element-wise functions, such as torch.sin(), torch.cos(), torch.exp(), and more, to apply mathematical functions to each element of a tensor:

In [43]:
# Element-wise functions
tensor = torch.tensor([0.0, 1.0, 2.0])
sin_result = torch.sin(tensor)
exp_result = torch.exp(tensor)

#### **5. Indexing and Slicing**
You can access specific elements or slices of a tensor using indexing and slicing operations:

In [44]:
# Indexing and slicing
tensor = torch.tensor([1, 2, 3, 4, 5])
element_at_index_2 = tensor[2]
slice = tensor[1:4]


PyTorch also has a bunch of built-in functions like torch.mul() (short for multiplication) and torch.add() to perform basic operations.

#### **6. Matrix Multiplication**
Matrix multiplication, also known as matrix product or dot product, is a fundamental operation in linear algebra. In PyTorch, you can perform matrix multiplication efficiently using various methods.

In [45]:
# Creating a tensor
tensor = torch.tensor([1, 2, 3])

# Element-wise multiplication: Each element multiplies its equivalent (index 0->0, 1->1, 2->2)
result = tensor * tensor

# Printing the tensor and its element-wise multiplication
print("Tensor:", tensor)
print("Element-wise Multiplication Result:", result)

Tensor: tensor([1, 2, 3])
Element-wise Multiplication Result: tensor([1, 4, 9])


In [46]:
# Create two matrices
matrix1 = torch.tensor([[1, 2], [3, 4]])
matrix2 = torch.tensor([[5, 6], [7, 8]])

# Perform matrix multiplication using torch.matmul()
result_matmul = torch.matmul(matrix1, matrix2)
result_matmul

tensor([[19, 22],
        [43, 50]])

*You can use the torch.matmul() function to perform matrix multiplication. It takes two tensors as arguments and returns their matrix product.*

In [47]:
# Perform matrix multiplication using the @ operator
result_operator = matrix1 @ matrix2
result_operator

tensor([[19, 22],
        [43, 50]])

*PyTorch also provides the @ operator, which is a convenient way to perform matrix multiplication.*

#### **Important**
***One of the most common errors in deep learning (shape errors)
Because much of deep learning is multiplying and performing operations on matrices and matrices have a strict rule about what shapes and sizes can be combined, one of the most common errors you'll run into in deep learning is shape mismatches.***

In [48]:
# Shapes need to be in the right way
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=torch.float32)

tensor_B = torch.tensor([[7, 10],
                         [8, 11],
                         [9, 12]], dtype=torch.float32)

torch.matmul(tensor_A, tensor_B) # (this will error)
# This will produce an error as expected because of the shape missmatch.

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

We can make matrix multiplication work between tensor_A and tensor_B by making their inner dimensions match.

One of the ways to do this is with a transpose (switch the dimensions of a given tensor).

You can perform transposes in PyTorch using either:

torch.transpose(input, dim0, dim1) - where input is the desired tensor to transpose and dim0 and dim1 are the dimensions to be swapped.
tensor.T - where tensor is the desired tensor to transpose

In [ ]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

In [ ]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

In [ ]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f"\nOutput shape: {output.shape}")

**You can also use torch.mm() which is a short for torch.matmul().**

In [ ]:
# torch.mm is a shortcut for matmul
torch.mm(tensor_A, tensor_B.T)

In [ ]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
torch.manual_seed(42)
# This uses matrix multiplication
linear = torch.nn.Linear(in_features=2, # in_features = matches inner dimension of input
                         out_features=6) # out_features = describes outer value
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

In [ ]:
torch.max(x), torch.min(x), torch.mean(x.type(torch.float32)), torch.sum(x)

## **Positional Min/Max**
You can use torch.argmax() and torch.argmin() functions to find the indices where the maximum and minimum values occur in a tensor, respectively. This is useful when you need to determine the positions of extreme values without necessarily retrieving the actual values. We will explore their practical applications further, especially when working with the softmax activation function in a later section.

Here's a concise explanation of how to use these functions:

- **torch.argmax(tensor)** returns the index of the maximum value in the tensor.
- **torch.argmin(tensor)** returns the index of the minimum value in the tensor.

In [ ]:
# Create a tensor
tensor = torch.arange(10, 100, 10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where max value occurs: {tensor.argmax()}")
print(f"Index where min value occurs: {tensor.argmin()}")

## **Change Tensor Datatype**

If we have one tensor in torch.float64 and another in torch.float32, we might encounter data type compatibility issues when performing certain operations. However, we can address this by adjusting the data type of the tensors using torch.Tensor.type(dtype=None), where the dtype parameter specifies the desired data type.

Let's start by creating a tensor and examining its data type (the default is torch.float32).

In [ ]:
# Create a tensor and check its datatype
sample_tensor = torch.arange(10., 100., 10.)
sample_tensor.dtype, sample_tensor

In [ ]:
# Create a float16 tensor
tensor_float16 = sample_tensor.type(torch.float16)
tensor_float16

In [ ]:
# Create a int8 tensor
tensor_int8 = sample_tensor.type(torch.int8)
tensor_int8

## **Reshaping, Stacking, Squeezing and Unsqueezing**
Often times you'll want to reshape or change the dimensions of your tensors without actually changing the values ins"ide them.

To do so, some popular methods are:

In [ ]:
# Create a Tensor
x = torch.arange(1., 10.)
x, x.shape

In [ ]:
# Add an extra dimention
x_reshaped = x.reshape(1, 9)

print("Reshaped Tensor:")
print(x_reshaped)
print("Shape of Reshaped Tensor:", x_reshaped.shape)

In [ ]:
# Add an extra dimension using reshape
x_reshaped = x.reshape(9, 1)

print("Reshaped Tensor:")
print(x_reshaped)
print("Shape of Reshaped Tensor:", x_reshaped.shape)

In [ ]:
# Change the view using .view()
z = x.view(1, 9)

print("Modified View Tensor:")
print(z)
print("Shape of Modified View Tensor:", z.shape)

*Remember though, changing the view of a tensor with torch.view() really only creates a new view of the same tensor.So changing the view changes the original tensor too.*

In [ ]:
# Changing z changes x
z[:, 0] = 5

print("Modified View Tensor z:")
print(z)
print("\nOriginal Tensor x:")
print(x)


If we wanted to stack our new tensor on top of itself five times, we could do so with torch.stack().

In [ ]:
# Original tensor
x = torch.tensor([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Stack tensors on top of each other along rows (dim=0)
x_stacked = torch.stack([x, x, x, x], dim=0)

# Stacked tensor
x_stacked

In [ ]:
# Stack tensors on top of each other along columns (dim=1)
x_stacked = torch.stack([x, x, x, x], dim=1)

# Display the stacked tensor
x_stacked

## **Removing Single Dimention**

#### How about removing all single dimensions from a tensor?

To do so you can use torch.squeeze() (I remember this as squeezing the tensor to only have dimensions over 1).

In [ ]:
x_reshaped

In [ ]:
# Reshaping x_reshaped 
x_reshaped = x_reshaped.reshape(1, 9)
x_reshaped

***When you use the squeeze() method on a tensor, it removes dimensions with size 1, effectively reducing the rank (number of dimensions) of the tensor. Let's apply squeeze() to the x_reshaped tensor:***

In [ ]:
# Squeeze the x_reshaped tensor
x_reshaped_squeezed = x_reshaped.squeeze()

# Display the squeezed tensor
x_reshaped_squeezed

In [ ]:
x_reshaped.squeeze().size()

In [ ]:
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()

print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

### **And to do the reverse of torch.squeeze() you can use torch.unsqueeze() to add a dimension value of 1 at a specific index.**

In [ ]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

### **Another essential tensor operation is rearranging the order of axes values, which can be achieved using torch.permute(input, dims). This function allows you to create a view of the input tensor with the specified dimensions, effectively rearranging the axes.**

In [ ]:
# Create tensor with specific shape
x_original = torch.rand(size=(224, 224, 3)) # Height, Width, Channels

# Permute the original tensor to rearrange the axis order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}") # Channels, Height, Width

In [ ]:
# Create a 3D tensor with random values
x = torch.randn(2, 3, 5)

# Use the .size() method to get the size (shape) of the tensor
size_of_x = x.size()
size_of_x

In [ ]:
x

In [ ]:
# Permute the dimensions of tensor x using torch.permute()
# The specified permutation order is (2, 0, 1)
permuted_x = torch.permute(x, (2, 0, 1))

# Get the size (shape) of the permuted tensor
size_of_permuted_x = permuted_x.size()

# Display the size of the permuted tensor
size_of_permuted_x

In [ ]:
x_original[0,0,0]

In [ ]:
x_permuted[0,0,0]

In [ ]:
# Modify the value at a specific position in the original tensor x_original
x_original[0, 0, 0] = 0.55

# Check the values at the same position in both the original and permuted tensors
value_in_original = x_original[0, 0, 0]
value_in_permuted = x_permuted[0, 0, 0]

value_in_original, value_in_permuted

*- We first modify the value at position (0, 0, 0) in the original tensor x_original and set it to 0.55.*

*- Then, we retrieve and store the values at the same position in both the original and permuted tensors.*

*- Finally, we display the values.*

## **Indexing**

In [ ]:
# Create a tensor using torch.arange() and reshape it
x = torch.arange(1, 10).reshape(1, 3, 3)

# Display the tensor x and its shape
x, x.shape

In [ ]:
# Access the first element along the first dimension of the tensor x
first_element = x[0]

# Printing the first element (a 2D slice) of the tensor x
first_element

In [ ]:
# Access the element at the first row and first column of the first 2D matrix in the tensor x
element = x[0][0]

# Printing the accessed element
element

In [ ]:
# Access the element at the first row and first column of the first 2D matrix in the tensor x
element = x[0, 0]
element

In [ ]:
# Access the element at the first row, first column, and first depth dimension of the tensor x
element = x[0, 0, 0]
element

In [ ]:
# Access the element at the first row, first column, and second depth dimension of the tensor x
element = x[0, 0, 1]
element

In [ ]:
# Access the element at the first row, second column, and second depth dimension of the tensor x
x[0, 1, 1]

In [ ]:
# Select all elements from the first column (index 0) along the second dimension of the tensor x
selected_column = x[:, 0]
selected_column

In [ ]:
# Get all values of 0th & 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

In [ ]:
# Get all values of the 0 dimension but only the 1 index value of the 1st and 2nd dimension
x[:, 1, 1]

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :] # same as x[0][0]


## **Tensors & NumPy**
PyTorch provides convenient methods for converting between NumPy arrays and PyTorch tensors:

- **torch.from_numpy(ndarray)** converts a NumPy array to a PyTorch tensor.
- **torch.Tensor.numpy()** converts a PyTorch tensor to a NumPy array.

These methods allow for seamless interaction between NumPy and PyTorch data structures.

In [ ]:
# Create a NumPy array with values ranging from 1.0 to 7.0
array = np.arange(1.0, 8.0)

# NumPy array and its shape
array, array.shape

In [ ]:
# Convert the NumPy array 'array' to a PyTorch tensor
tensor = torch.from_numpy(array)

# PyTorch tensor and its shape
tensor, tensor.shape

In [ ]:
# Change the array, keep the tensor
array = array + 1
array, tensor

In [ ]:
# Create a PyTorch tensor 'tensor' filled with ones and having dtype=float32
tensor = torch.ones(7)

# Convert the PyTorch tensor to a NumPy array 'numpy_tensor'
numpy_tensor = tensor.numpy()

# Display the PyTorch tensor and the NumPy array
tensor, numpy_tensor

## **Reproducibility in PyTorch**
Randomness is a powerful tool, but sometimes you need to reduce it for the sake of reproducibility. Reproducibility allows you and others to obtain the same or highly similar results when running the same code on different machines.

Consider a scenario where you've developed an algorithm achieving a specific performance level, and you want your colleague to validate your findings on their computer. How can you ensure consistent results?

This is where reproducibility comes into play. In PyTorch, you can take steps to control randomness, making your experiments more predictable.

To demonstrate this, let's start by creating two random tensors. Since they are random, you might expect them to be different, right?

Here's an example of ensuring reproducibility in PyTorch.

In [ ]:
# Create two random tensors, random_tensor_A and random_tensor_B
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

# Display the values of Tensor A and Tensor B
print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")

# Check if Tensor A equals Tensor B (element-wise, anywhere)
are_equal = random_tensor_A == random_tensor_B

# Print the result of the equality check
print(f"Does Tensor A equal Tensor B? (anywhere)")
are_equal

As expected, the previous random tensors had different values. But what if you wanted to create two random tensors with the same "flavor" of randomness? In other words, you want the tensors to still contain random values, but these values should be consistent.

This is where torch.manual_seed(seed) comes into play. You can specify an integer value (such as 42 or any other) as the seed, and it will determine the characteristics of randomness.

Let's demonstrate this by creating some random tensors with the same flavor.

In [ ]:
# Import the random module
import random

# Set the random seed to ensure reproducibility
RANDOM_SEED = 42  # You can change this value to experiment with different random seeds

# Set the random seed for PyTorch
torch.manual_seed(seed=RANDOM_SEED)

# Create a random tensor with the specified random seed
random_tensor_C = torch.rand(3, 4)
random_tensor_C

In [ ]:
# Have to reset the seed every time a new rand() is called
# Without this, tensor_D would be different to tensor_C
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

In [ ]:
print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

## **Device Compatibility**

In [ ]:
# This command, '!nvidia-smi', is used to display information about the NVIDIA GPU(s) installed on the system. 
# It provides details such as GPU model, memory usage, temperature, and more. 
# It's a useful tool for monitoring GPU status and can be helpful for tasks like deep learning training.
!nvidia-smi

#### **Checking Device**
Checking the device (CPU or GPU) is essential for efficient utilization of hardware resources. It allows for faster computation on GPUs, effective memory management, and compatibility with deep learning libraries, ultimately improving performance in machine learning tasks.

In [ ]:
# Check if a GPU is available for use with PyTorch
gpu_available = torch.cuda.is_available()

# Print the result (True if GPU is available, False otherwise)
gpu_available

#### **Setting Device**
Setting a device in deep learning is the act of specifying whether computations should occur on a CPU or GPU. A "cpu" device implies that all operations, including model training and inference, are performed on the Central Processing Unit. In contrast, a "cuda" or GPU device offloads computations to the Graphics Processing Unit, which excels at parallel tasks like deep learning. The choice depends on hardware availability, model size, memory requirements, and compatibility with libraries, impacting training speed and resource utilization. It allows developers to optimize deep learning workflows for their specific hardware configuration.

In [ ]:
# Check if a GPU is available, and if so, set the device type to "cuda"; otherwise, use "cpu"
device = "cuda" if torch.cuda.is_available() else "cpu"

# Print the selected device type
device

In [ ]:
# Count the number of devices
torch.cuda.device_count()

#### **Putting tensors (and models) on the GPU**
**Note:** Putting a tensor on GPU using to(device) (e.g. some_tensor.to(device)) returns a copy of that tensor, e.g. the same tensor will be on CPU and GPU. To overwrite tensors, reassign them:

some_tensor = some_tensor.to(device)

In [ ]:
# Create tensor (default on CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor not on GPU
print(tensor, tensor.device)

# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

#### **Moving tensors back to the CPU**

In [ ]:
# If tensor is on GPU, can't transform it to NumPy (this will error)
tensor_on_gpu.numpy()

In [ ]:
# Instead, copy the tensor back to cpu
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

In [ ]:
tensor_on_gpu

## **Closing Thoughts**
In this comprehensive guide, we've explored the fundamental concepts of PyTorch, a powerful deep learning framework, and its practical applications. We started by introducing PyTorch and its essential libraries, followed by a hands-on journey through tensors, their operations, and various tensor types. We discussed GPU utilization for faster computations and how to ensure reproducibility in your experiments. Whether you're a beginner in deep learning or an experienced practitioner, this guide serves as a valuable resource for harnessing the capabilities of PyTorch in your machine learning projects. With its flexibility, performance optimization, and rich ecosystem, PyTorch continues to be a driving force in the world of deep learning. Now armed with this knowledge, you're well-equipped to dive deeper into PyTorch and explore its vast potential in your data science endeavors.

**Please feel free to ask in the comment section if you have any confusion or questions.**

#### Here are some of the contributions I've made on Kaggle:

- **[Comprehensive Guide on NumPy for Beginners](https://www.kaggle.com/code/tanvirnwu/comprehensive-guide-on-numpy-for-beginners#Learn-More)**
- **[Comprehensive Guide on NumPy for Beginners](https://www.kaggle.com/code/tanvirnwu/boolean-in-python-with-example-and-explanation)**
- **[Dictionary in Python with Examples & Explanations](https://www.kaggle.com/code/tanvirnwu/dictionary-in-python-with-examples-explanations)**
- **[List in Python for Beginners](https://www.kaggle.com/code/tanvirnwu/list-in-python-for-beginners)**
- **[A Brief Introduction of Graph Neural Network (GNN): Concepts, Types, and Uses](https://www.kaggle.com/discussions/general/449125#2493256)**
- **[Essential Python Libraries for Data Visualization](https://www.kaggle.com/discussions/getting-started/450857)**

### **Please Inspire me by your Upvotes, Comment & Follow. Thanks!**